[package]
name = "ansic"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi = {path = "../ansi", features = ["no_panic", "crepr"]}

[lib]
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cbindgen = "0.29.0"